# Generated by Django 2.1.1 on 2020-02-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
