# Generated by Django 3.0.3 on 2020-02-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_style', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('CVV_number', models.IntegerField()),
                ('card_zip', models.IntegerField()),
                ('card_expdate', models.IntegerField()),
            ],
        ),
    ]
