# Generated by Django 3.0.4 on 2020-03-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20200311_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Lunch', max_length=50),
            preserve_default=False,
        ),
    ]
