# Generated by Django 3.0.3 on 2020-02-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_food_style_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cardholder_name',
            new_name='cardholder_FirstName',
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder_LastName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
    ]
