# Generated by Django 3.0.3 on 2020-02-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20200227_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Style',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
