# Generated by Django 3.0.3 on 2020-02-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20200227_2121'),
        ('tables', '0005_item_style_menu_payment_restaurant_restaurant_style_review'),
    ]

    operations = [
    ]
