# Generated by Django 3.0.4 on 2020-04-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20200417_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_style',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item_style',
            name='style_id',
        ),
        migrations.RemoveField(
            model_name='restaurant_style',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='restaurant_style',
            name='style_id',
        ),
        migrations.DeleteModel(
            name='Customer_Style_Preference',
        ),
        migrations.DeleteModel(
            name='Food_Style',
        ),
        migrations.DeleteModel(
            name='Item_Style',
        ),
        migrations.DeleteModel(
            name='Restaurant_Style',
        ),
    ]
