# Generated by Django 3.0.3 on 2020-02-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_merge_20200228_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Style',
        ),
    ]
