# Generated by Django 3.0.4 on 2020-04-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
