# Generated by Django 3.0.3 on 2020-02-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_delete_food_style'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
