# Generated by Django 3.0.4 on 2020-04-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20200420_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
