# Generated by Django 3.0.4 on 2020-04-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
