# Generated by Django 3.0.4 on 2020-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_remove_orderitem_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/static/NoImageFound.jpg', upload_to='images/'),
        ),
    ]
