# Generated by Django 3.0.4 on 2020-04-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/static/NoImageFound.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/static/NoImageFound.jpg', upload_to='images/'),
        ),
    ]
