# Generated by Django 3.0.4 on 2020-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_auto_20200423_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(default='no changes', max_length=500),
            preserve_default=False,
        ),
    ]
