# Generated by Django 3.0.4 on 2020-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_remove_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='/static/NoImageFound.jpg', upload_to='images/'),
        ),
    ]
