# Generated by Django 3.0.4 on 2020-04-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_orderitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tables.Restaurant'),
            preserve_default=False,
        ),
    ]
