# Generated by Django 3.0.4 on 2020-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
