# Generated by Django 3.0.4 on 2020-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_address_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
