# Generated by Django 3.0.4 on 2020-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_auto_20200423_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
