# Generated by Django 3.0.4 on 2020-04-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_auto_20200424_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripeid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
