# Generated by Django 3.0.4 on 2020-04-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_auto_20200428_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.Review'),
        ),
    ]
