# Generated by Django 3.0.4 on 2020-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_order_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='header',
            field=models.CharField(default='Good', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
