# Generated by Django 3.0.4 on 2020-08-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_auto_20200506_1507'),
        ('tables', '0025_payment_customer'),
    ]

    operations = [
    ]
